version: '2'
services:
    mongodb:
        image: autopilotpattern/mongodb:latest
        command: containerpilot mongod --replSet=pilot
        restart: always
        network_mode: "bridge"
        mem_limit: 512m
        build: .
        env_file: _env
        links:
            - consul:consul
        ports:
            - 27017

    consul:
        image: consul:v0.6.4
        command: agent -dev -ui -client=0.0.0.0
        restart: always
        container_name: consul
        network_mode: "bridge"
        mem_limit: 128m
        ports:
            - 8500:8500
        expose:
            - 53
            - 8300
            - 8301
            - 8302
            - 8400
            - 8500

